Add makers page
sparcs-kaist/new-ara-web pull request #191
Opened 2020-11-25 16:42 UTC by TriangleYJ

만든이들 페이지를 만들었지만, 실명 맵핑은 하지 않은 상태입니다 (PM분들 제외 직책도 마찬가지)
참고로 원 디자인에서는 배경이 약간 회색조를 띄고 있으나 그냥 흰색 배경에 카드 테두리를 씌웠습니다

2020-11-27 18:08 UTC, victory-jooyon requested changes
netlify 미리보기로 봤을때 기준으로
1. description 안의 내용은 가운데 정렬이 아닌 왼쪽 정렬 되었으면 좋겠습니다.
2. description 내용이 길때와 짧을때에 따라서 Project와 Description 의 위치가 바뀝니다. description 내용이 들어가는 박스 넓이가 고정되어야할것 같아요.
3. Position 이 너무 연해서 아예 안보입니다. 제플린과는 조금 달라질수있겠지만 직책 글씨색을 조금 더 진하게 해주시면 좋을 것 같아요.
4. 그리고 뱃지가 로켓인건, 제플린에 있는 체크표시보다 더 좋은 것 같습니다! 로켓 모양 그대로 유지해도 좋을 것 같아요.

2020-11-28 07:08 UTC, HelloWorld017 commented
작은 사이즈 (ex: width: 467) 에서는 align이 맞지 않는 거 같긴 한데 상관 없을 듯 합니다. 혹시라도 꼭 맞추시고 싶다 하시면 p 태그를 grid 밖으로 빼서 desc-side 클래스를 다 추가하는 것만으로도 꽤 괜찮게 보이는 듯 하네요.

i18n 도 되면 더 좋을 것 같긴 하나, 크레딧 페이지라서 굳이 적용할 필요가 있나 싶긴 합니다.
일단 저는 이대로 머지돼도 좋을 것 같아요.

2020-11-28 07:08 UTC, HelloWorld017 approved these changes

2020-11-28 07:52 UTC, TriangleYJ commented
> netlify 미리보기로 봤을때 기준으로
> 
> 1. description 안의 내용은 가운데 정렬이 아닌 왼쪽 정렬 되었으면 좋겠습니다.
> 2. description 내용이 길때와 짧을때에 따라서 Project와 Description 의 위치가 바뀝니다. description 내용이 들어가는 박스 넓이가 고정되어야할것 같아요.
> 3. Position 이 너무 연해서 아예 안보입니다. 제플린과는 조금 달라질수있겠지만 직책 글씨색을 조금 더 진하게 해주시면 좋을 것 같아요.
> 4. 그리고 뱃지가 로켓인건, 제플린에 있는 체크표시보다 더 좋은 것 같습니다! 로켓 모양 그대로 유지해도 좋을 것 같아요.

2020-11-28 08:01 UTC, merged