Feature/filterandordering
sparcs-kaist/new-ara-web pull request #325
Opened 2022-05-12 12:11 UTC by greenina

2022-05-12 12:44 UTC, TriangleYJ reviewed
현재 netlify에서 쿼리는 바뀌는 것 같은데, 정렬은 안되는 것 같아요 (아직 dev 백엔드가 반영이 안된 건가요..?)
그리고 communication 관린 쿼리 이름이 조금 긴 것 같은데, 혹시 다른 분들께서 줄이는 게 나을 것 같다고 생각하시면 백엔드 수정하도록 할께요

2022-05-19 08:31 UTC, Xxix2580 requested changes

2022-05-19 08:31 UTC, Xxix2580 commented on src/views/Board.vue
> +      selectedFilter: this.$route.query.communication_article__school_response_status ? '답변 완료' : (this.$route.query.communication_article__school_response_status__lt ? '답변 미완' : '전체 보기')
영문 대응이 안되는 것 같습니다!

2022-05-19 13:22 UTC, TriangleYJ commented
좋은 것 같습니다! 머지전 몇개 확인해 주시면 좋을 것 같아요
1. `console.log` 지워주세요! 
2. 뒤로가기 눌렀을때 필터가 존재함에도 모든 게시글이 보여지는 것 같습니다. 처음에 글 가져올 때 필터 반영해서 가져오게 해야 할 것 같아요
3. `i18n` 이용해서 영문 대응 해 준 다음 머지 해주면 될 것 같습니다

2022-05-20 11:51 UTC, greenina commented
@TriangleYJ 반영했습니다 :)

2022-05-20 12:57 UTC, TriangleYJ approved these changes
LGTM!

2022-05-20 12:57 UTC, TriangleYJ commented on src/api/board.js
> +  console.log('filter :', filter)
여기만 지워주시면 될 것 같아요!

2022-06-02 10:41 UTC, TriangleYJ commented
@greenina PR 머지 리마인더 드립니다!

2022-06-02 14:45 UTC, merged