Feature/channeltalk
sparcs-kaist/new-ara-web pull request #391
Opened 2023-07-12 08:26 UTC by KoYejune0302

2023-07-18 19:29 UTC, 000wan requested changes
👍

2023-07-18 19:29 UTC, 000wan commented on .env.example
> +VUE_APP_API_HOST= # api 주소 (명시하지 않으면 dev/prod 서버 api로 연결)
채널톡 플러그인 키 env 변수로 만들었는데 github secrets에 추가해야 합니다. 저는 권한이 없어서 아마 PM님이 해주셔야 할 것 같아요. @injoonH 그 후 `.github/workflows/github-actions.sh` 파일도 수정 필요합니다.

2023-07-19 01:28 UTC, injoonH commented
아래 에러가 뜨면서 로그인이 안 되는데 확인 부탁드립니다.

```
Uncaught (in promise) Error: Redirected when going from "/" to "/login" via a navigation guard.
```

2023-07-19 02:15 UTC, 000wan commented
netlify preview에서 로그인 할때 조금 문제 있었던 걸로 기억하는데 그거 때문 아닐까요? 저는 잘 작동해요

2023-07-19 02:16 UTC, 000wan approved these changes

2023-07-26 11:05 UTC, merged