Bug/footer
sparcs-kaist/new-ara-web pull request #430
Opened 2023-11-23 15:03 UTC by KoYejune0302

로그아웃 후 이용약관 누를 시 창이 닫히지 않는 버그

2023-12-20 07:43 UTC, 000wan requested changes

2023-12-20 07:43 UTC, 000wan commented on src/router/auth.js
> +    }
이렇게 했을 때 [글 공유](https://deploy-preview-430--ara-beta-dev.netlify.app/post/7176)하면 외부에서 페이지 들어갈 때마다 (로그인 안되어있는 경우) alert가 항상 떠서 불편할 수 있을것 같아요. 랜딩페이지도 있는데 이건 없어도 괜찮지 않을까요❔

2024-01-09 11:44 UTC, KoYejune0302 commented on src/router/auth.js
> +    }
alert가 떠서 불편한 부분도 있겠지만 랜더링 페이지로 가더라도 이게 로그인 때문인지 다른 이유 때문인지 알려주는게 더 좋을것 같아요. 그리고 sso로 한번 로그인하면 계속 유지될거라 처음 한번 정도만 뜰거 같아요.

2024-01-15 09:55 UTC, 000wan commented on src/router/auth.js
> +    }
네 approve 할게요~

2024-01-15 09:56 UTC, 000wan approved these changes
👍

2024-03-18 15:28 UTC, merged